### ISSUE TITLE
Possible to check actual discogs wantlist?

### ISSUE THREAD

**Issue by LieberGott** [beudbeud/discoger#1]
Hi Adrien, 
I tested it on Windows 10 using docker desktop.

I was building the image using this command
`docker build -t my-discoger-image C:\discoger`

After I was running the container using this command:
`docker container run -v C:\discoger:/root/.config/discoger my-discoger-image`

What I didn't understand yet, can the bot only check the list that you can set up via the telegram bot input or can it also check your actual waitlist on Discogs?

thanks a lot!

**Comment by beudbeud** [comment]
for now it's  check only list you have build from bot, but i can add possibility to tracking wantlist or custom list
